version: "3"

vars:
  hostList: >
    google.com cisco.com ibm.com 
    amazon.com microsoft.com www.ourcommons.ca 
    stackoverflow.com github.com
tasks:
  build:
    desc: build app
    dir: cmd/certcheck
    cmds:
      - rm -f ../../build/certcheck
      - go build -o ../../build/certcheck .
  test:
    desc: test app
    dir: build
    cmds:
      - task: build
      - time echo "{{.hostList}}" | ./certcheck
      - go test -v ../...
      - echo {{.hostList}}
