version: "3"

tasks:
  build:
    desc: build app
    dir: cmd/certcheck
    cmds:
      - rm -f ../../build/certcheck
      - go build -o ../../build/certcheck .
  test:
    desc: test app
    dir: build
    cmds:
      - task: build
      - echo "google.com cisco.com ibm.com amazon.com microsoft.com" | ./certcheck
      - go test -v ../...
